hmcts/ucd-adoption-prototype

app/views/alpha-tidy-up/not-eligible.html

undo test 2

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/5-hearing-details.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-other-names.html

Backup Wednesday morning

---

app/views/alpha-tidy-up/two-applicants/task-list-2-multiple.html

Updated link to first applicant personal details on task list page

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/screening-questions/lived-uk.html
app/views/alpha-tidy-up/screening-questions/lived-uk4.html

Jays branch

---

app/views/alpha-tidy-up/routes.js

First applicant personal details journey

---

app/data/session-data-defaults.js
app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-occupation.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-other-names-monica-backup copy.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-date-birth.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-gender.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-name.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-nationality.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-occupation.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-other-names.html
app/views/alpha-tidy-up/two-applicants/task-list-2-multiple.html

Last commit of the day Monica

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-date-birth.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-gender.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-nationality.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-occupation.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-other-names.html

Last update Wednesday

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-address.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-contact.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-find-address.html
app/views/alpha-tidy-up/two-applicants/task-list-2-multiple.html
app/views/includes/buttons0.html

Section 5 

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-address2.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-address.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-find-address.html

section 5 links

---

app/views/alpha-tidy-up/about-application/number-of-applicants.html
app/views/alpha-tidy-up/about-application/number-of-children.html
app/views/alpha-tidy-up/screening-questions/number-of-children copy.html
app/views/alpha-tidy-up/screening-questions/number-of-children.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-other-names.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-address.html

Changes to number of children on application details

---

app/views/alpha-tidy-up/about-application/number-of-children.html

Content update on number of children

---

app/views/alpha-tidy-up/about-application/number-of-children.html

Removal of full stop on number of children

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/screening-questions/start-second.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-address.html

Section 5 changes 

---

app/views/alpha-tidy-up/about-application/number-of-applicants.html
app/views/alpha-tidy-up/about-application/number-of-children.html
app/views/alpha-tidy-up/routes.js

Application details

---

app/views/alpha-tidy-up/about-application/number-of-children.html
app/views/alpha-tidy-up/routes.js

Changes to error message on how many children page

---

app/views/alpha-tidy-up/about-application/number-of-children.html
app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-contact.html

First applicant contact page error messages

---

app/views/alpha-tidy-up/screening-questions/start-placement.html
app/views/alpha-tidy-up/screening-questions/start-second.html

Tidy up of start pages

---

app/views/alpha-tidy-up/screening-questions/start-placement.html
app/views/alpha-tidy-up/screening-questions/start-second.html

Tidy up on start pages

---

app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-address.html

Changes to second applicant address page

---

app/views/alpha-tidy-up/about-application/number-of-applicants.html
app/views/alpha-tidy-up/about-application/number-of-children.html
app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-find-address.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-name.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-name.html

Changes to buttons on number of children and number of applicants

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-date-birth.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-gender.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-nationality.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-occupation.html

First applicant personal details pages

---

app/views/alpha-tidy-up/screening-questions/start-second.html

start second content change

---

app/views/alpha-tidy-up/about-application/number-of-children.html
app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-other-names.html

Removal of gender page

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/task-list.html

New task list

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/task-list.html

task list update 

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/task-list.html

Changes to task list page

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-contact.html

second applicant contact error corrected

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/task-list.html

Changes to task list to remove links that don't work yet

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/screening-questions/married.html
app/views/alpha-tidy-up/screening-questions/under-18.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-contact.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-contact.html

Changes to eligibility questions

---

app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-address2.html

second applicant address 2 error message

---

app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-address.html
app/views/alpha-tidy-up/two-applicants/about-you/first-applicant-name.html
app/views/alpha-tidy-up/two-applicants/about-you/second-applicant-address.html

Path fix on first and second applicant address pages

---

app/views/alpha-tidy-up/about-application/number-of-applicants-2.html
app/views/alpha-tidy-up/routes.js
app/views/alpha-tidy-up/task-list-2.html

New number of applicants page

---

app/views/alpha-tidy-up/about-application/number-of-applicants-2.html

Small copy change on number of applicants

---

app/views/alpha-tidy-up/about-application/number-of-applicants-old.html
app/views/alpha-tidy-up/about-application/number-of-applicants.html

New number of applicants journey

---

app/views/index.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Changes to index.html and error message on under-18 page

---

app/views/index.html

Index change

---

app/views/version-1/index.html

Update of version-1 index page

---

app/views/version-1/index.html

Trying to fix errors

---

app/views/index.html

Fixing index.html

---

app/views/version-1/applicants/first-applicant-occupation.html
app/views/version-1/routes.js

First applicant occupation page

---

app/views/version-1/applicants/first-applicant-contact.html

Branch test

---

app/views/version-1/applicants/first-applicant-contact.html
app/views/version-1/routes.js

First applicant contact page

---

app/views/version-1/applicants/second-applicant-same-address.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Task list updates

---

app/views/version-1/task-list.html

Task list update

---

app/views/version-1/task-list-new.html

New task list design proposal

---

app/views/version-1/task-list-one-upload.html
app/views/version-1/task-list-two-uploads.html

Two alternatives for task list page

---

app/views/version-1/task-list-one-upload.html

One upload section task list

---

app/views/version-1/applicants/second-applicant-same-address.html
app/views/version-1/routes.js

Error message on second applicant same address page

---

app/data/session-data-defaults.js

Deletion of old files

---

app/data/session-data-defaults.js
app/views/version-1/children/mother-name.html
app/views/version-1/routes.js
app/views/version-1/task-list-old.html
app/views/version-1/task-list.html

Update to task list and birth mother details

---

app/views/version-1/applicants/first-applicant-nationality.html
app/views/version-1/applicants/second-applicant-nationality.html
app/views/version-1/routes.js

Add different countries on nationality pages

---

app/views/version-1/applicants/first-applicant-nationality.html
app/views/version-1/children/mother-nationality.html
app/views/version-1/routes.js

Nationality pages changes

---

app/views/version-1/children/mother-have-address.html
app/views/version-1/children/mother-occupation.html
app/views/version-1/children/mother-why-no-address.html
app/views/version-1/routes.js

Final changes to birth mother name page

---

app/views/version-1/children/child-adoption-certificate.html
app/views/version-1/children/child-date-birth.html
app/views/version-1/children/child-gender.html
app/views/version-1/children/child-name.html
app/views/version-1/children/child-nationality.html
app/views/version-1/children/child-nationalityX.html
app/views/version-1/children/child-time-birth.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

section 10 & 11 page creation

---

app/data/session-data-defaults.js
app/views/version-1/applicants/first-applicant-enter-address-manually.html
app/views/version-1/applicants/second-applicant-enter-address-manually.html
app/views/version-1/children/mother-alive.html
app/views/version-1/children/mother-have-address.html
app/views/version-1/children/mother-name.html
app/views/version-1/children/mother-nationality.html
app/views/version-1/children/mother-occupation.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Updates to the mother details journey and manual address pages

---

app/views/version-1/routes.js

nationality route update

---

app/views/version-1/children/mother-address-postcode.html
app/views/version-1/routes.js

Birth mother postcode lookup page

---

app/data/session-data-defaults.js
app/views/version-1/routes.js
app/views/version-1/task-list.html

Changes to defaults file, task list and routes

---

app/views/version-1/children/child-nationality.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Tweaks to child nationality and task list

---

app/views/version-1/routes.js

Tidying up of routes

---

app/views/version-1/children/mother-alive.html
app/views/version-1/children/mother-find-address.html
app/views/version-1/routes.js

Mother address updates

---

app/views/version-1/children/mother-find-address.html

Tweak on mother-find-address page

---

app/views/version-1/children/mother-manual-address.html
app/views/version-1/routes.js

Mother manual address page

---

app/views/version-1/routes.js

Correction of child's error message

---

app/views/version-1/routes.js

Trying to fix app crash error

---

app/data/session-data-defaults.js
app/views/version-1/children/applicant-adoption-agency-name.html
app/views/version-1/children/applicant-social-worker-address.html
app/views/version-1/children/applicant-social-worker-email.html
app/views/version-1/children/applicant-social-worker-enter-address-manually.html
app/views/version-1/children/applicant-social-worker-find-address.html
app/views/version-1/children/applicant-social-worker-name.html
app/views/version-1/children/applicant-social-worker-number.html
app/views/version-1/children/applicant-social-worker-team-email.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

section 17 pages

---

app/views/version-1/children/applicant-social-worker-team-email.html

needs route fixed
```
[ ] Yes
[ ] No
```

new team email page

---

app/views/version-1/children/mother-cya-details.html

New check your answers page mid-journey

---

app/views/version-1/children/child-gender.html
app/views/version-1/children/child-name.html
app/views/version-1/routes.js

Section 10

---

app/views/version-1/children/father-address-postcode.html
app/views/version-1/children/father-alive.html
app/views/version-1/children/father-find-address.html
app/views/version-1/children/father-have-address.html
app/views/version-1/children/father-in-certificate.html
app/views/version-1/children/father-manual-address.html
app/views/version-1/children/father-name.html
app/views/version-1/children/father-nationality.html
app/views/version-1/children/father-occupation.html
app/views/version-1/children/father-why-no-address.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Father details pages

---

app/views/version-1/children/applicant-social-worker-team-emailx.html
app/views/version-1/routes.js

team email changes

---

app/data/session-data-defaults.js

Quick change to session data defaults

---

app/views/version-1/routes.js

Routes.js tidy up

---

app/data/session-data-defaults.js
app/views/version-1/children/solicitor-helping.html
app/views/version-1/routes.js

Solicitor first page created

---

app/views/version-1/applicants/first-applicant-nationality.html
app/views/version-1/routes.js

Fixing error messages on nationality

---

app/views/version-1/applicants/first-applicant-address.html
app/views/version-1/applicants/first-applicant-find-address.html
app/views/version-1/applicants/second-applicant-address.html
app/views/version-1/applicants/second-applicant-find-address.html
app/views/version-1/applicants/second-applicant-nationality.html
app/views/version-1/routes.js

Fixed H1 on first and second applicant address pages

---

app/views/version-1/applicants/first-applicant-contact.html
app/views/version-1/applicants/second-applicant-contact.html
app/views/version-1/routes.js

Contact pages for both applicants error messages update

---

app/views/version-1/routes.js

Error panic

---

app/views/version-1/routes.js

Trying to commit my branch changes again

---

app/views/version-1/applicants/first-applicant-enter-address-manually.html
app/views/version-1/routes.js

Working on error messages on manual address

---

app/views/version-1/applicants/first-applicant-enter-address-manually.html
app/views/version-1/applicants/second-applicant-enter-address-manually.html
app/views/version-1/children/applicant-social-worker-enter-address-manually.html
app/views/version-1/children/father-manual-address.html
app/views/version-1/children/mother-manual-address.html
app/views/version-1/routes.js

Manual address error messages for all entities

---

app/views/version-1/children/applicant-social-worker-find-address.html
app/views/version-1/children/child-social-worker-find-address.html
app/views/version-1/children/solicitor-firm-name.html
app/views/version-1/routes.js

section 19 start

---

app/views/version-1/children/applicant-social-worker-team-email.html
app/views/version-1/routes.js

Applicant social worker team email update with error messages

---

app/views/version-1/children/child-nationality.html
app/views/version-1/children/father-nationality.html
app/views/version-1/children/mother-nationality.html
app/views/version-1/routes.js

Changes to nationality pages

---

app/views/version-1/applicants/first-applicant-nationality.html
app/views/version-1/children/child-nationality.html
app/views/version-1/children/father-nationality.html
app/views/version-1/children/mother-nationality.html
app/views/version-1/routes.js

Nationality pages for child, birth mother and birth father

---

app/views/version-1/routes.js

Change of routing on child's nationality page

---

app/views/version-1/children/child-adoption-certificate.html
app/views/version-1/children/child-adoption-certificate2.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Section 19 adop cert content

---

app/views/version-1/children/applicant-adoption-agency-details.html
app/views/version-1/children/applicant-adoption-agency-name.html
app/views/version-1/routes.js

adop 241 and 242

---

app/views/version-1/children/child-name-old.html
app/views/version-1/children/child-name.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Birth certificate details journey ready to review

---

app/views/version-1/children/mother-find-address.html
app/views/version-1/task-list.html

Birth mother details journey completed for review

---

app/data/session-data-defaults.js
app/views/version-1/children/mother-have-address.html

Birth mother's journey corrections following Lisa's feedback

---

app/views/version-1/children/applicant-adoption-agency-details.html
app/views/version-1/children/applicant-adoption-agency.html
app/views/version-1/routes.js

Adoption agency details page

---

app/views/version-1/applicants/first-applicant-occupation.html
app/views/version-1/applicants/second-applicant-occupation.html
app/views/version-1/application/check-your-answers.html
app/views/version-1/children/father-address-postcode.html
app/views/version-1/children/father-alive.html
app/views/version-1/children/father-have-address.html
app/views/version-1/children/father-name.html
app/views/version-1/children/father-nationality.html
app/views/version-1/children/father-occupation.html
app/views/version-1/children/mother-address-postcode.html
app/views/version-1/children/mother-nationality.html
app/views/version-1/eligibility/cannot-apply-married.html
app/views/version-1/eligibility/cannot-apply-over-18.html
app/views/version-1/eligibility/start-placement.html
app/views/version-1/registration/start.html
app/views/version-1/registration/start2.html
app/views/version-1/registration/start4.html
app/views/version-1/registration/start5.html
app/views/version-1/routes.js

Birth father details journey ready for review by Lisa

---

app/views/version-1/children/solicitor-details.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Task list fix for other parent showing in progress

---

app/views/version-1/children/orders-court-check-your-answers.html

Update to check your answers page for court orders

---

app/views/version-1/children/applicant-other-adoption-agency.html
app/views/version-1/children/solicitor-helping.html

Divs correction on a few pages

---

app/views/version-1/children/solicitor-details.html

Copy update on solicitor details page

---

app/data/session-data-defaults.js
app/views/version-1/children/other-parent-exists.html
app/views/version-1/task-list.html

Chage to other parent's details title of page

---

app/views/version-1/applicants/date-child-moved-in.html
app/views/version-1/routes.js

adop 90 -content

---

app/views/version-1/applicants/date-child-moved-in.html
app/views/version-1/applicants/first-applicant-date-birth.html
app/views/version-1/applicants/second-applicant-date-birth.html

Correction of divs on date pages for applicants and date child moved in

---

app/data/session-data-defaults.js
app/views/version-1/children/sibling-choose-sibling.html
app/views/version-1/children/sibling-court-order-exists.html
app/views/version-1/children/sibling-exists.html
app/views/version-1/children/sibling-name.html
app/views/version-1/children/sibling-order-case-number.html
app/views/version-1/children/sibling-order-court.html
app/views/version-1/children/sibling-order-date.html
app/views/version-1/children/sibling-order-type.html
app/views/version-1/children/sibling-summary.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Start of sibling details journey

---

app/views/version-1/children/sibling-check-your-answers.html
app/views/version-1/children/sibling-choose-sibling.html
app/views/version-1/children/sibling-summary.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Sibling details journey completed, pending content

---

app/views/version-1/children/sibling-check-your-answers.html

Minor correction on sibling-check-your-answers

---

app/views/version-1/routes.js

Change to routes to fix sibling details bug

---

app/views/version-1/children/father-have-address.html
app/views/version-1/children/mother-have-address.html
app/views/version-1/children/orders-summary.html
app/views/version-1/children/other-parent-have-address.html
app/views/version-1/children/sibling-change-name.html
app/views/version-1/children/sibling-remove-court-order.html
app/views/version-1/children/sibling-summary.html
app/views/version-1/children/x-multiple-children-same-mother.html
app/views/version-1/routes.js

Hint text on mother, father and other parent address question

---

app/views/version-1/children/father-address-postcode.html
app/views/version-1/children/father-manual-address-international.html
app/views/version-1/routes.js

Section 19

---

app/views/version-1/children/sibling-change-name.html
app/views/version-1/children/sibling-summary.html
app/views/version-1/routes.js

Change name and remove court order journeys

---

app/views/version-1/children/sibling-change-order-case-number.html
app/views/version-1/children/sibling-change-order-court.html
app/views/version-1/children/sibling-change-order-type.html
app/views/version-1/children/sibling-check-your-answers.html
app/views/version-1/routes.js

Work on siblings journey

---

app/views/version-1/task-list.html

Task list correction from test on macbook

---

app/views/version-1/children/sibling-change-order-date.html
app/views/version-1/routes.js

Change order date page

---

app/views/version-1/routes.js

Fix on routes

---

app/views/version-1/children/sibling-change-order-date.html
app/views/version-1/routes.js

Change placement order date

---

app/views/version-1/children/other-parent-manual-address.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Error message on manual address page for other parent

---

app/views/version-1/task-list.html

Task list update from macbook

---

app/views/version-1/task-list.html

Task list update from iMac

---

app/views/version-1/children/other-parent-exists.html
app/views/version-1/children/solicitor-details.html
app/views/version-1/routes.js

content changes

---

app/views/version-1/applicants/first-applicant-enter-address-manually.html
app/views/version-1/applicants/first-applicant-name.html
app/views/version-1/applicants/second-applicant-enter-address-manually.html
app/views/version-1/applicants/second-applicant-name.html
app/views/version-1/children/applicant-adoption-agency-details-2.html
app/views/version-1/children/applicant-adoption-agency-details.html
app/views/version-1/children/child-name.html
app/views/version-1/children/child-social-worker-details.html
app/views/version-1/children/father-manual-address-international.html
app/views/version-1/children/father-manual-address.html
app/views/version-1/children/father-name.html
app/views/version-1/children/mother-manual-address-international.html
app/views/version-1/children/mother-manual-address.html
app/views/version-1/children/mother-name.html
app/views/version-1/children/other-parent-manual-address-international.html
app/views/version-1/children/other-parent-name.html
app/views/version-1/children/sibling-change-name.html
app/views/version-1/children/sibling-choose-sibling.html
app/views/version-1/children/sibling-name.html
app/views/version-1/children/solicitor-details.html

all added apart from choose sibling page
```
[ ] Yes
[ ] No
```

error message lines

---

app/views/version-1/Check-pay-and-submit/check-your-answers.html

Uppercase fix

---

app/views/version-1/Check-pay-and-submit/check-your-answers.html

Fixing uppercase folder name

---

app/views/version-1/Check-pay-and-submit/check-your-answers.html
app/views/version-1/Check-pay-and-submit/declaration.html
app/views/version-1/Check-pay-and-submit/payment.html

Check, pay and submit updates

---

app/views/version-1/check-pay-and-submit-2/check-your-answers.html
app/views/version-1/check-pay-and-submit-2/declaration.html
app/views/version-1/check-pay-and-submit-2/payment.html

Trying to fix issues with uppercase folder

---

app/views/version-1/children/child-adoption-certificate.html

Correction of error message on child-adoption-certificate page

---

app/views/version-1/routes.js

Fix of error formatting on sibling-summmary

---

app/views/version-1/check-pay-and-submit/declaration.html

Declaration update

---

app/views/version-1/check-pay-and-submit/confirmation.html
app/views/version-1/check-pay-and-submit/payment.html

confirmation page content

---

app/views/version-1/check-pay-and-submit/need-help-with-fees-ref1.html
app/views/version-1/check-pay-and-submit/need-help-with-fees1.html
app/views/version-1/check-pay-and-submit/payment.html

help with fees ref page amendments

---

app/views/version-1/routes.js
app/views/version-1/task-list.html
app/views/version-1/upload/child-documents-upload.html

Upload pages

---

app/views/version-1/check-pay-and-submit/declaration.html
app/views/version-1/check-pay-and-submit/help-with-fees-applied.html
app/views/version-1/routes.js

declaration page to statement of truth

---

app/views/version-1/check-pay-and-submit/declaration.html
app/views/version-1/eligibility/apply-for-help-with-fees.html
app/views/version-1/routes.js

Declaration

---

app/views/version-1/eligibility/apply-for-help-with-fees.html
app/views/version-1/routes.js

Eligibility help with fees journey

---

app/views/version-1/eligibility/apply-for-help-with-fees.html

Content update on help with fees apply page

---

app/views/version-1/routes.js

Update to routes

---

app/views/version-1/check-pay-and-submit/need-help-with-fees-ref.html

Copy change on need help with fees page

---

app/views/version-1/check-pay-and-submit/need-help-with-fees-ref.html

Update to need-help-with-fees-ref page

---

app/views/version-1/routes.js

update routes for error message for hwfs

---

app/views/version-1/check-pay-and-submit/need-help-with-fees-ref.html

Update on hint text on help with fees

---

app/views/version-1/check-pay-and-submit/declaration.html
app/views/version-1/eligibility/apply-for-help-with-fees.html
app/views/version-1/eligibility/do-you-need-help-with-fees.html
app/views/version-1/routes.js

Update on help with fees pages

---

app/views/version-1/check-pay-and-submit/help-with-fees-send-app.html

Help with fees routing update

---

app/views/version-1/check-pay-and-submit/declaration.html
app/views/version-1/eligibility/apply-for-help-with-fees.html
app/views/version-1/eligibility/do-you-need-help-with-fees.html

Do you need help with fees content change

---

app/views/version-1/check-pay-and-submit/declaration.html
app/views/version-1/routes.js

Error messages update

---

app/views/version-1/check-pay-and-submit/declaration.html
app/views/version-1/routes.js

Declaration updates

---

app/views/version-1/check-pay-and-submit/declaration.html

Copy change on declaration checkbox

---

app/views/version-1/check-pay-and-submit/get-hwf-reference.html
app/views/version-1/routes.js

error message fixed

---

app/views/version-1/children/orders-summary.html
app/views/version-1/children/sibling-summary.html

Order summary and sibling summary pages content update

---

app/views/version-1/applicants/first-applicant-date-birth.html
app/views/version-1/applicants/first-applicant-name.html
app/views/version-1/applicants/first-applicant-other-names.html
app/views/version-1/applicants/second-applicant-date-birth.html
app/views/version-1/applicants/second-applicant-name.html
app/views/version-1/applicants/second-applicant-other-names.html
app/views/version-1/children/child-date-birth.html
app/views/version-1/children/child-name.html
app/views/version-1/children/father-alive.html
app/views/version-1/children/father-name.html
app/views/version-1/children/mother-alive.html
app/views/version-1/children/mother-name.html
app/views/version-1/children/other-parent-name.html
app/views/version-1/children/sibling-name.html
app/views/version-1/routes.js

Bug fixes to prepare for research

---

app/views/version-1/children/father-occupation.html
app/views/version-1/children/mother-occupation.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Task list updates with completed status - not completed yet

---

app/views/version-1/routes.js

routes fix

---

app/views/version-1/applicants/first-applicant-enter-address-manually.html
app/views/version-1/applicants/second-applicant-enter-address-manually.html
app/views/version-1/children/father-manual-address-international.html
app/views/version-1/children/father-manual-address.html
app/views/version-1/children/other-parent-manual-address-international.html
app/views/version-1/children/other-parent-manual-address.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Change of input names so that they're unique throughout the prototype

---

app/views/version-1/check-pay-and-submit/get-hwf-reference.html
app/views/version-1/children/family-court-finder.html
app/views/version-1/routes.js
app/views/version-1/task-list.html

Added some links to family court finder and help with fees pages

---

app/views/index.html

Change to index page

---

app/views/version-1/check-pay-and-submit/process-payment.html
app/views/version-1/eligibility/start-placement.html
app/views/version-1/routes.js

start placement updated

---

app/views/header-ex-ui.html
app/views/layout-ex-ui.html
app/views/version-1/ex-ui/index.html

ExUI first screen

---

app/views/version-1/check-pay-and-submit/check-your-answers.html
app/views/version-1/routes.js

Slight change to routes and update to check your answers wip page

---

app/views/version-1/check-pay-and-submit/check-your-answers.html
app/views/version-1/children/father-have-address.html
app/views/version-1/children/father-in-certificate.html
app/views/version-1/children/mother-have-address.html
app/views/version-1/children/other-parent-exists.html
app/views/version-1/children/other-parent-have-address.html
app/views/version-1/routes.js

Check your answers work in progress

---

app/views/version-1/check-pay-and-submit/check-your-answers.html
app/views/version-1/children/other-parent-have-address.html

Check your answers update

---

app/views/version-1/applicants/first-applicant-other-names.html
app/views/version-1/children/family-court-finder.html
app/views/version-1/routes.js

Change to first applicant other names error message

---

app/views/version-1/applicants/second-applicant-other-names copy.html
app/views/version-1/applicants/second-applicant-other-names.html
app/views/version-1/routes.js

Other names error messages

---

app/views/version-1/children/family-court-finder.html

Family court finder update

---

app/views/version-1/children/family-court-finder.html

Changes to family court finder

---

app/views/version-1/check-pay-and-submit/check-your-answers.html
app/views/version-1/registration/start5.html

Work in progress on check your answers

---

app/views/version-1/check-pay-and-submit/check-your-answers.html
app/views/version-1/check-pay-and-submit/confirmation.html

Changes to confirmation and check your answers pages

---

app/views/includes/newfooter.html
app/views/includes/newheader.html
app/views/includes/next-steps-old.html
app/views/includes/next-steps.html
app/views/version-1/x-ui/index.html
app/views/version-1/x-ui/tab.html
app/views/version-1/x-ui/task-list.html

X-UI task list view starting point

---

app/views/includes/next-steps.html
app/views/version-1/x-ui/task-list.html

xUI task list

---

app/views/version-1/check-pay-and-submit/check-your-answers.html

Check your answers temporary title update

---

app/views/includes/buttons-xui.html
app/views/includes/newfooter.html
app/views/version-1/routes.js
app/views/version-1/x-ui/children/child-with-errors.html

xui child birth certificate details page

---

app/views/version-1/applicants/second-applicant-other-names.html

Fix on add 'second' names

---

app/views/version-1/x-ui/children/child.html

Child details page

---

app/views/includes/sw-header.html
app/views/version-1/children/applicant-adoption-agency-details-2.html
app/views/version-1/children/applicant-adoption-agency-details.html
app/views/version-1/children/child-social-worker-details.html
app/views/version-1/children/sibling-check-your-answers.html
app/views/version-1/routes.js
app/views/version-1/task-list.html
app/views/version-1/x-ui/children/sibling-check-your-answers.html
app/views/version-1/x-ui/index.html
app/views/version-1/x-ui/social-worker/social-worker-case-list.html
app/views/version-1/x-ui/task-list.html

Removal of solicitor details and sibling court and date

---

app/views/version-1/task-list.html

Little change on task list

---

app/views/version-1/applicants/first-applicant-other-names.html
app/views/version-1/applicants/second-applicant-other-names.html

Other names added intructions for both applicants

---

app/views/layout-signed-in.html
app/views/layout-signed-out.html

Link for payment screen and card number on footer

---

app/views/version-1/x-ui/case-worker/case-worker-orders.html
app/views/version-1/x-ui/case-worker/case-worker-prospective-parents.html

Prospective parents case worker xui tab

---

app/views/version-1/check-pay-and-submit/check-your-answers.html
app/views/version-1/x-ui/case-worker/case-worker-prospective-parents.html

Removal of nationality from check your answers

---

app/views/version-1/children/child-adoption-certificate.html
app/views/version-1/x-ui/case-worker/case-worker-orders.html
app/views/version-1/x-ui/case-worker/case-worker-other-parties.html
app/views/version-1/x-ui/case-worker/index.html

Recovery of child adoption certificate page

---

app/views/version-1/x-ui/case-worker/case-worker-history.html
app/views/version-1/x-ui/case-worker/index.html

Case worker tabs added

---

app/views/version-1/x-ui/case-worker/case-worker-birth-parents.html
app/views/version-1/x-ui/case-worker/case-worker-history.html
app/views/version-1/x-ui/case-worker/case-worker-orders.html
app/views/version-1/x-ui/case-worker/case-worker-other-parties.html
app/views/version-1/x-ui/case-worker/case-worker-prospective-parents.html
app/views/version-1/x-ui/case-worker/index.html

Payments tab added

---

app/views/version-1/x-ui/case-worker/case-worker-payments.html

Payments page

---

app/views/version-1/routes.js
app/views/version-1/x-ui/case-worker/case-worker-manage-documents.html
app/views/version-1/x-ui/case-worker/case-worker-upload.html

Manage documents pages

---

app/views/version-1/x-ui/case-worker/case-worker-upload.html

Documents upload page

---

app/views/version-1/routes.js

Removal of court and date from sibling orders

---

app/views/includes/sw-header.html
app/views/layout-ex-ui.html
app/views/version-1/routes.js
app/views/version-1/task-list.html
app/views/version-1/x-ui/case-worker/index.html

Changes to task list to have section 5 in only 1 line

---

app/views/version-1/check-pay-and-submit/check-your-answers.html
app/views/version-1/x-ui/case-worker/case-worker-prospective-parents.html
app/views/version-1/x-ui/case-worker/index.html

Check your answers additional names example

---

app/views/header-signed-in.html
app/views/header-signed-out.html
app/views/includes/sw-header.html
app/views/layout-ex-ui.html
app/views/version-1/check-pay-and-submit/check-your-answers.html
app/views/version-1/children/sibling-court-order-exists.html
app/views/version-1/children/sibling-exists.html
app/views/version-1/eligibility/apply-for-help-with-fees.html
app/views/version-1/eligibility/cannot-apply-applicant.html
app/views/version-1/eligibility/child-can-be-adopted.html
app/views/version-1/eligibility/do-you-need-help-with-fees.html
app/views/version-1/eligibility/domicile.html
app/views/version-1/eligibility/lived-uk.html
app/views/version-1/eligibility/married.html
app/views/version-1/eligibility/under-18.html
app/views/version-1/eligibility/under-21.html
app/views/version-1/upload/child-documents-upload.html
app/views/version-1/x-ui/case-worker/case-worker-message-radios.html
app/views/version-1/x-ui/case-worker/case-worker-messages.html
app/views/version-1/x-ui/case-worker/case-worker-send-message.html
app/views/version-1/x-ui/case-worker/index.html

Case worker messages, check your answers and eligibility header changes

---

app/views/version-1/eligibility/start-placement.html

court-placement-order-link

---

app/views/includes/newfooter.html
app/views/layout-signed-out.html

footer - almost complete

---

app/views/version-1/routes.js
app/views/version-1/x-ui/case-worker/case-worker-message-radios.html
app/views/version-1/x-ui/case-worker/case-worker-message-sent.html
app/views/version-1/x-ui/case-worker/case-worker-send-message.html

Case worker messages journey

---

app/views/layout-signed-out.html

footer-covid-brexit-addition

---

app/views/version-1/x-ui/case-worker/case-worker-message-radios.html

Messages journey case worker

---

app/views/version-1/x-ui/case-worker/case-worker-message-radios.html
app/views/version-1/x-ui/case-worker/case-worker-message-sent.html

Case worker messages content update

---

app/views/version-1/check-pay-and-submit/check-your-answers.html

Check your answers update at the bottom of the page

---

app/views/layout-signed-in.html
app/views/layout-signed-out.html

update to footer and feedback link

---

app/views/version-1/children/child-sex.html

Child sex hint text update

---

app/views/version-1/task-list-multiple-children.html
app/views/version-1/x-ui/task-list.html

Multiple children task list added

---

app/assets/sass/application.scss
app/views/r2/citizen-dashboard/index.html

Citizen dashboard

---

app/views/r2/citizen-dashboard/index.html

Dashboard changes

---

app/views/r2/citizen-dashboard/index.html
app/views/r2/citizen-dashboard/view-application.html

Updates to citizen dashboard

---

app/views/r2/citizen-dashboard/all-applications.html
app/views/r2/citizen-dashboard/index.html

All applications starting to take shape

---

app/views/r2/citizen-dashboard/all-applications.html
app/views/r2/citizen-dashboard/citizen-dashboard-mary.html

All applications page and updated dashboard for another child

---

app/views/r2/citizen-dashboard/all-applications-table.html
app/views/r2/citizen-dashboard/all-applications.html
app/views/r2/citizen-dashboard/citizen-dashboard-mary.html
app/views/r2/citizen-dashboard/index.html

All applications done with summary list styles for responsive purposes

---

app/views/r2/application/number-of-children.html
app/views/r2/eligibility/under-18.html
app/views/r2/routes.js
app/views/r2/task-list.html

Multiple children starting point

---

app/views/index.html
app/views/r2/children/x-multiple-children-same-mother.html
app/views/version-1/routes.js
app/views/version-1/x-ui/case-worker/case-worker-add-note.html
app/views/version-1/x-ui/case-worker/index.html

Citizen dashboard add notes section

---

app/views/version-1/x-ui/case-worker/index.html

Changes to summary tab on case worker xui

---

app/views/version-1/x-ui/case-worker/index.html

Removal of link on 'submitted' status on summary page

---

app/views/version-1/x-ui/case-worker/index.html

case worker index page change

---

app/views/r2/index.html
app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-add-note.html
app/views/r2/x-ui/case-worker/case-worker-birth-parents.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-message-radios.html
app/views/r2/x-ui/case-worker/case-worker-message-sent.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/case-worker-send-message.html
app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html
app/views/r2/x-ui/case-worker/case-worker-upload-old.html
app/views/r2/x-ui/case-worker/case-worker-upload.html
app/views/r2/x-ui/case-worker/index.html

Case worker changes to documents page and moved to r2

---

app/views/layout-xui-judges-view.html
app/views/r2/routes.js
app/views/r2/task-list.html
app/views/r2/x-ui/case-worker/case-worker-case-list.html
app/views/r2/x-ui/case-worker/case-worker-case-list2.html
app/views/r2/x-ui/case-worker/case-worker-intention-oppose.html
app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html

Case worker case list page and update of task list

---

app/views/r2/x-ui/case-worker/case-worker-case-list.html

Case worker case list page in construction

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html

Case worker xui documents journey updated

---

app/views/r2/x-ui/case-worker/case-worker-documents.html

Case worker documents update

---

app/views/r2/x-ui/case-worker/case-worker-documents.html

Manage documents link removed from bottom of documents tab

---

app/views/r2/x-ui/case-worker/case-worker-messages.html

Messages new tab content

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-manage-documents.html
app/views/r2/x-ui/case-worker/case-worker-messages-select-person.html

Documents tab and messages updates

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-manage-documents.html
app/views/r2/x-ui/case-worker/case-worker-messages-select-person.html

ExUI documents tab final design

---

app/views/includes/sw-header.html

Case list link added to the header

---

app/views/r2/x-ui/case-worker/case-worker-case-list2.html

Attempt to commit after unauthorised error

---

app/views/r2/task-list.html
app/views/r2/x-ui/case-worker/case-worker-case-list.html
app/views/r2/x-ui/case-worker/index.html

Case worker case list court

---

app/views/r2/x-ui/case-worker/case-worker-manage-documents.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-upload.html

Documents and messages updates on case worker xui pages

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html

ExUI other parties tab

---

app/views/r2/application/applicant-adoption-agency-details-2.html
app/views/r2/application/applicant-other-adoption-agency.html
app/views/r2/application/case-worker-other-parties.html
app/views/r2/application/local-authority-details.html
app/views/r2/routes.js
app/views/r2/task-list.html
app/views/r2/x-ui/case-worker/index.html

Jay's updates on LA/SW and case worker other parties tab

---

app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html

Court orders by email added to applicants tab on xui case worker flow

---

app/views/version-1/children/sibling-court-order-exists.html
app/views/version-1/children/sibling-exists.html

Siblings errors fixed

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html

Upload statement list of people updated with real values

---

app/views/r2/children/sibling-relationship.html
app/views/r2/children/sibling-summary.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html

Sibling and case worker other parties changes

---

app/views/r2/x-ui/case-worker/case-worker-message-radios.html
app/views/r2/x-ui/case-worker/case-worker-messages-select-person.html
app/views/r2/x-ui/case-worker/case-worker-send-message.html

messages edit

---

app/views/r2/index.html

R2 index file

---

app/views/r2/task-list.html

Contact us link removed from task list

---

app/views/r2/children/sibling-relationship.html
app/views/r2/children/sibling-summary.html

Sibling court orders updated copy for sw portal

---

app/views/r2/children/sibling-court-order-exists.html
app/views/r2/task-list.html

Siblings and task list changes

---

app/views/r2/children/sibling-order-case-number.html

Removal of hint text on siblings flow

---

app/views/r2/x-ui/case-worker/case-worker-messages-select-person.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-send-message.html

Case worker messages update

---

app/views/r2/task-list.html
app/views/version-1/task-list.html

Task list changes to ask for postcode from second applicant

---

app/views/r2/applicants/first-applicant-contact.html
app/views/r2/applicants/second-applicant-contact.html
app/views/version-1/applicants/first-applicant-contact.html
app/views/version-1/applicants/second-applicant-contact.html

Updated contact details pages for applicants

---

app/views/r2/routes.js

Change on routes to make siblings go to the right location on task list

---

app/views/r2/children/sibling-order-type.html
app/views/r2/children/sibling-summary.html
app/views/r2/routes.js

Sibling orders change to radio buttons for order type

---

app/views/r2/children/sibling-change-order-type.html
app/views/r2/routes.js

Order type change screen changes

---

app/views/r2/applicants/second-applicant-language-selector.html

Second applicant language selector label update

---

app/views/r2/check-pay-and-submit/check-your-answers.html

Check your answers with language options

---

app/views/r2/eligibility/start-placement.html
app/views/r2/la-portal/task-list.html

Start page link fix

---

app/views/r2/check-pay-and-submit/confirmation.html

Feedback link on confirmation page

---

app/views/r2/la-portal/child-date-birth.html
app/views/r2/la-portal/task-list.html

Task list changes to remove h2

---

app/views/r2/applicants/first-applicant-change-address.html
app/views/r2/applicants/second-applicant-change-address.html

Change address for other applicant screens

---

app/views/r2/applicants/first-applicant-change-address-confirmation.html
app/views/r2/applicants/first-applicant-change-address.html
app/views/r2/applicants/second-applicant-change-address-confirmation.html
app/views/r2/applicants/second-applicant-change-address.html
app/views/r2/check-pay-and-submit/pay-and-submit.html
app/views/r2/la-portal/sibling-order-type.html
app/views/r2/routes.js
app/views/r2/task-list.html

Change address other applicants confirmation pages

---

app/views/r2/check-pay-and-submit/confirmation.html
app/views/r2/check-pay-and-submit/pay-and-submit.html
app/views/r2/routes.js

Pay and submit and confirmation pages

---

app/views/r2/application/child-social-worker-details.html
app/views/r2/check-pay-and-submit/check-your-answers-backup.html
app/views/r2/check-pay-and-submit/check-your-answers.html

Chack your answers update

---

app/views/r2/check-pay-and-submit/pay-and-submit.html
app/views/r2/children/family-court-finder.html

Family court finder and pay and submit updates based on ticket ADOP-956

---

app/views/r2/application/child-social-worker-details.html
app/views/r2/routes.js

Child social worker email error messages update

---

app/views/r2/routes.js

Updated routes

---

app/views/r2/la-portal/task-list.html
app/views/r2/la-portal/upload.html

Link to the current upload page on LA portal task list

---

app/views/r2/application/child-social-worker-details.html

Child social worker details error message correction

---

app/views/r2/application/child-social-worker-details.html

Correction on error formatting on child social worker

---

app/views/r2/check-pay-and-submit/check-your-answers.html
app/views/r2/la-portal/check-your-answers.html
app/views/r2/la-portal/task-list.html
app/views/r2/routes.js

Updates to LA portal check your answers and ticket ADOP-966

---

app/views/r2/la-portal/check-your-answers.html
app/views/r2/la-portal/sibling-court-order-exists.html

Check your answers and siblings

---

app/views/r2/la-portal/check-your-answers.html
app/views/r2/routes.js

Update to check your answers

---

app/views/r2/routes.js

Fix to siblings flow

---

app/views/r2/la-portal/upload.html

Upload content update

---

app/views/r2/la-portal/check-your-answers.html

Heroku test

---

app/views/r2/routes.js

Siblings relationship error message fixed

---

app/views/r2/la-portal/access-questions.html

Access questions change

---

app/views/r2/la-portal/access-questions.html

Access questions content update

---

app/views/r2/la-portal/access-questions.html

Access questions on LA portal error message

---

app/views/r2/la-portal/Secure-changes.html

La  portal changes

---

app/views/r2/index.html

Index R2 updated with case list

---

app/views/r2/la-portal/access-questions.html
app/views/r2/la-portal/negative-scenario.html
app/views/r2/routes.js

negative scenario mock up

---

app/views/r2/la-portal/access-questions.html
app/views/r2/la-portal/confirmation.html
app/views/r2/routes.js

confirmation page changes

---

app/views/r2/la-portal/check-your-answers.html
app/views/r2/la-portal/confirmation.html
app/views/r2/la-portal/upload.html

confirmation / upload/ check answers changes

---

app/views/r2/la-portal/task-list.html

Change to task list only show button if upload is done

---

app/views/r2/la-portal/sibling-relationship.html

Sibling relationship removal of step siblings

---

app/views/r2/la-portal/father-alive.html
app/views/r2/la-portal/mother-alive.html
app/views/r2/la-portal/sibling-order-case-number.html

parents alive hint text and sibling order hint text

---

app/views/r2/la-portal/sibling-summary.html

Sibling summary

---

app/views/r2/la-portal/sibling-order-type.html

Siblings order type

---

app/views/r2/la-portal/access-questions.html
app/views/r2/la-portal/check-your-answers.html

Check your answers - case number added

---

app/views/r2/la-portal/check-your-answers.html

Check your answers update with court case reference number

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html

Adop 875 - other parties tab update

---

app/views/r2/applicants/first-applicant-nationality.html
app/views/r2/applicants/second-applicant-nationality.html
app/views/r2/la-portal/child-nationality.html
app/views/r2/la-portal/father-nationality.html
app/views/r2/la-portal/mother-nationality.html
app/views/r2/routes.js

Nationality add a different country error message change

---

app/views/r2/la-portal/sibling-relationship.html

Siblings relationship fix

---

app/views/r2/la-portal/check-your-answers.html
app/views/r2/la-portal/upload.html

Check your answers and upload pages updated with new content

---

app/views/r2/routes.js

Change save as draft button action on sibling court orders

---

app/views/r2/la-portal/upload.html

Updated copy on uploads page

---

app/views/r2/la-portal/upload.html
app/views/r2/x-ui/case-worker/case-worker-case-list.html
app/views/r2/x-ui/case-worker/case-worker-message-send-and-reply.html

Uploads and case worker case list content updates

---

app/views/r2/la-portal/upload.html
app/views/r2/x-ui/case-worker/case-worker-message-send-and-reply.html

Upload updated page and start of xui send and reply messages

---

app/views/layout-xui.html
app/views/r2/x-ui/case-worker/case-worker-message-send-and-reply.html

Macbook changes

---

app/views/layout-xui.html
app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-message-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-message-reply-required.html
app/views/r2/x-ui/case-worker/case-worker-message-send-and-reply.html
app/views/r2/x-ui/case-worker/case-worker-messages.html

Reply to messages - incomplete flow

---

app/data/session-data-defaults.js
app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-message-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-messages.html

Caseworker messages reply flow

---

app/views/r2/la-portal/orders-summary.html

Change in typo order-orders on orders summary

---

app/views/r2/la-portal/statement-of-truth.html
app/views/r2/routes.js

LA portal statement of truth

---

app/views/r2/x-ui/case-worker/case-worker-messages.html

Case worker messages link copy change

---

app/views/r2/la-portal/orders-summary.html

Correction of typo on orders summary

---

app/views/r2/la-portal/orders-summary.html

Orders summary revert of copy to previous version

---

app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-upload-old.html
app/views/r2/x-ui/case-worker/case-worker-upload.html

Case worker documents ticket

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html

Case worker documents flow - final version

---

app/views/r2/x-ui/case-worker/case-worker-documents.html

Case worked upload documents - date and name added to documents tab

---

app/views/r2/x-ui/case-worker/case-worker-case-list.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html
app/views/r2/x-ui/case-worker/case-worker-upload.html

Case worker documents content update

---

app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-upload.html

Hint text added to upload case worker page

---

app/views/r2/index.html
app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html

Index update

---

app/views/r2/index.html

Tidy up of R2 index page

---

app/views/r2/x-ui/case-worker/case-worker-case-list.html
app/views/r2/x-ui/case-worker/case-worker-upload.html

Changes to case worker case list

---

app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html

Select person xui upload message

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html

Some reverted changes to case worker other parties

---

app/views/r2/x-ui/case-worker/case-worker-case-list.html

Case list updates

---

app/views/r2/x-ui/case-worker/case-worker-case-list.html

Swap of order of columns on case worker case list

---

app/views/r2/routes.js

Upload documents journey ready to be moved to BA refine me

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-birth-parents.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/index.html

Messages next steps pointing to the right page

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-messages-select-person.html
app/views/r2/x-ui/case-worker/case-worker-messages.html

Case worker messages ready to move to BA refine me

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-edit-document.html

Edit documents page added

---

app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html

Fix of broken buttons on select person upload flow case worker

---

app/views/r2/la-portal/statement-of-truth.html

Ticket 1101 removal of date from statement of truth

---

app/views/r2/la-portal/statement-of-truth.html

Update statement of truth on LA portal with confirmation checkbox

---

app/views/r2/x-ui/case-worker/case-worker-add-note.html
app/views/r2/x-ui/case-worker/case-worker-birth-parents.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-edit-document.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-intention-oppose.html
app/views/r2/x-ui/case-worker/case-worker-message-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-message-radios.html
app/views/r2/x-ui/case-worker/case-worker-message-reply-required.html
app/views/r2/x-ui/case-worker/case-worker-message-send-and-reply.html
app/views/r2/x-ui/case-worker/case-worker-message-sent.html
app/views/r2/x-ui/case-worker/case-worker-messages-select-person.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/case-worker-send-message.html
app/views/r2/x-ui/case-worker/case-worker-statements-select-respondent.html
app/views/r2/x-ui/case-worker/case-worker-upload.html
app/views/r2/x-ui/case-worker/index.html

ADOP-1215 add child's name to top of every page on ExUI

---

app/views/r2/x-ui/case-worker/case-worker-add-note.html

Update to add-notes page

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-notes-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-notes.html

Notes and add notes on case worker xui

---

app/views/r2/x-ui/case-worker/case-worker-notes-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-notes.html

Updates to add note screens on case worker

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html

Correspondence tab case worker updates

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html

Correspondence copy update

---

app/views/r2/x-ui/case-worker/case-worker-manage-documents.html
app/views/r2/x-ui/case-worker/case-worker-notes-check-your-answers.html

Check your answers for add a case note copy update

---

app/views/r2/la-portal/upload.html

Removal of rogue sentence from LA portal upload page

---

app/views/includes/buttons-laportal-save-as-draft.html
app/views/r2/la-portal/statement-of-truth.html

Sprint 4 changes

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-directions.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-type-of-order.html
app/views/r2/x-ui/case-worker/index.html

Gatekeeping first few pages

---

app/views/r2/la-portal/statement-of-truth.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-case-management-order.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-type-of-order.html

Statement of truth

---

app/views/r2/la-portal/statement-of-truth.html

Statement of truth final push

---

app/views/r2/x-ui/case-worker/case-worker-gatekeeping-case-management-order.html

Gatekeeping case management order

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-directions.html
app/views/r2/x-ui/case-worker/case-worker-send-message.html

Send messages flow update

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-birth-parents.html
app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/case-worker-seek-further-information-reply-by.html
app/views/r2/x-ui/case-worker/case-worker-seek-further-information-send-message.html
app/views/r2/x-ui/case-worker/case-worker-seek-further-information.html
app/views/r2/x-ui/case-worker/index.html
app/views/r2/x-ui/case-worker/next-steps-case-worker.html

Adop-1021/1022

---

app/views/r2/la-portal/check-your-answers.html
app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-case-management-order.html
app/views/r2/x-ui/case-worker/case-worker-send-message-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-send-message.html

Statement of truth routing

---

app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-edit-document.html

Documents tab and edit documents page updates

---

app/views/r2/x-ui/case-worker/case-worker-upload.html

Upload documents page update

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html

Updated correspondence tab

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-annexa-required-by.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-birth-parents-details-required-by.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-case-management-order.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-type-of-order.html

Create gatekeeping order journey

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html

Case worker correspondence and documents content updates

---

app/views/includes/buttons-laportal-save-as-draft.html
app/views/r2/la-portal/task-list.html
app/views/r2/routes.js

Fix of application error

---

app/views/r2/la-portal/task-list.html
app/views/r2/routes.js

Fix of task list routing on LA portal

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-messages-reply-message.html

Messages update

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-birth-parents-details-required-by.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-judge.html

Gatekeeping journey update

---

app/views/version-1/check-pay-and-submit/confirmation.html

Link added to version1 - confirmation page

---

app/views/r2/check-pay-and-submit/confirmation.html

Confirmation page on R2

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html

Next steps link for messages updated

---

app/views/version-1/check-pay-and-submit/confirmation.html

Updated confirmation page

---

app/views/r2/x-ui/case-worker/case-worker-gatekeeping-judge.html

Manage orders journey without error messages

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-allocate-judge.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/index.html

Allocate judge and place it on summary page

---

app/views/r2/x-ui/case-worker/case-worker-messages-send-message.html
app/views/r2/x-ui/case-worker/old-message-flow/case-worker-messages11082022.html

Messages flow work in progress

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html

Change to visited statuses on links

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-case-management-order.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/index.html
app/views/r2/x-ui/case-worker/old-message-flow/case-worker-messages11082022.html

Allocate a judge on next steps

---

app/views/r2/x-ui/case-worker/case-worker-gatekeeping-allocate-judge.html

Allocate a judge page

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html

address fields added

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-judge.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-manage-orders.html
app/views/r2/x-ui/case-worker/old-message-flow/case-worker-gatekeeping-case-management-order-checked-items.html
app/views/r2/x-ui/case-worker/old-message-flow/case-worker-gatekeeping-judge.html
app/views/r2/x-ui/case-worker/test.html

Gatekeeping order journey update

---

app/data/session-data-defaults.js
app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-allocate-judge.html
app/views/r2/x-ui/case-worker/index.html

Allocate judge changes

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/index.html

Alphabetical rearrangement of next steps dropdown

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-messages.html

Correspondence descrption and document lines added

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/index.html

Addition of 'create order' link to next steps

---

app/views/r2/x-ui/case-worker/case-worker-messages.html

Messages next steps update

---

app/views/r2/routes.js

Change error path on routes

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-4-1.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-4-2.html

Final adoption orderjourney update

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/case-worker-seek-further-information-send-message.html
app/views/r2/x-ui/case-worker/index.html
app/views/r2/x-ui/case-worker/next-steps-case-worker.html

need further info edits

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-4-3.html

Final adoption order update

---

app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-4-3.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-5.html

Final adoption order prep

---

app/views/r2/routes.js

Final adoption order updates

---

app/data/session-data-defaults.js
app/views/r2/routes.js

Routing of screen 5 to previous screen on final adoption order

---

app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-1.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-2.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-3.html

Final adoption order tweaks

---

app/data/session-data-defaults.js
app/views/r2/x-ui/case-worker/case-worker-amend-applicant-details.html

Amend details page

---

app/data/session-data-defaults.js
app/views/r2/x-ui/case-worker/case-worker-amend-applicant-details.html

Amend app details edits

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html

Amen app details linked to app tab

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-refer-to-judge.html
app/views/r2/x-ui/case-worker/index.html

Case worker summary page labels removed

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/index.html

Allocate judge flow

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/amend-applicant-details-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html

amend applicant check your answers page

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-final-adoption-3.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-refer-to-judge.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/index.html

Create an order removed from next step dropdown list

---

app/views/r2/x-ui/case-worker/index.html

Changes to summary page case worker to remove social workers details

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-2.html

Gatekeeping order mid-journey

---

app/assets/sass/application.scss
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-2.html

Case worker gatekeeping order page 2

---

app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-2.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-3.html

Gatekeeping order still missing check your answers and recipient screen

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-3.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/index.html

Case issue removed from next step dropdown

---

app/data/session-data-defaults.js
app/views/r2/x-ui/case-worker/amend-case-details-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-amend-case-details.html

Small fix on divs and dates on amend case details

---

app/data/session-data-defaults.js
app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-2.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-check-your-answers.html

Allocated judge change on gatekeeping order

---

app/data/session-data-defaults.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-2.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-3.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-check-your-answers-old.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-creation-manage-orders.html

Gatekeeping order check your answers

---

app/views/r2/x-ui/case-worker/index.html

Back to branch monica

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/case-worker-seek-further-information.html
app/views/r2/x-ui/case-worker/index.html
app/views/r2/x-ui/case-worker/next-steps-case-worker.html

Seek further information and multiple tabs on summary page

---

app/views/r2/x-ui/case-worker/case-worker-seek-further-information.html

Seek further info copy update

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-4-select-recipient.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/index.html

Gatekeeping order creation

---

app/data/session-data-defaults.js
app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-orders.html

Orders tab

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-3.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-4-select-recipient.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-6-order-preview.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/index.html

Changes to nav bar on case worker and gatekeeping order

---

app/views/r2/x-ui/case-worker/case-worker-amend-applicant-details.html

Amend applicants details correct pattern for radio buttons expand

---

app/views/r2/x-ui/case-worker/case-worker-amend-applicant-details.html

Correction of typo

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html

Other parties tweaks

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html

Other person with parental responsbility copy change

---

app/views/r2/x-ui/case-worker/case-worker-correspondence.html
app/views/r2/x-ui/case-worker/case-worker-documents.html
app/views/r2/x-ui/case-worker/case-worker-history.html
app/views/r2/x-ui/case-worker/case-worker-messages.html
app/views/r2/x-ui/case-worker/case-worker-notes.html
app/views/r2/x-ui/case-worker/case-worker-orders.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html
app/views/r2/x-ui/case-worker/case-worker-payments.html
app/views/r2/x-ui/case-worker/case-worker-prospective-parents.html
app/views/r2/x-ui/case-worker/index.html

Amend other parties details added to the next step dropdown

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html

Person with PR additional question added

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-1.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-2.html

Start of general directions order flow

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-2.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-3-1-general.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-3-2-production.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-3-3-disclosure.html

General directions order flow

---

app/views/r2/routes.js

Small change in routes for general directions order

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-1.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-2.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-3-1-general.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-4-1-warning-notices.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-5-1-general-check-your-answers.html

General directions flow

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-2.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-3-0.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-5-1-general-check-your-answers.html

General directions order flow update

---

app/views/r2/x-ui/case-worker/case-worker-general-directions-order-1.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-5-1-general-check-your-answers.html

Changes to page 1 from Lisa's content

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-4-1-general.html

Fix of hearings route

---

app/views/r2/x-ui/case-worker/case-worker-general-directions-order-3.html

General directions hearing page update

---

app/views/r2/x-ui/case-worker/case-worker-general-directions-order-2-alt.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-5-2-production-check-your-answers.html
app/views/r2/x-ui/case-worker/case-worker-other-parties.html

Changes to case worker other parties

---

app/views/r2/x-ui/case-worker/case-worker-other-parties.html

other parties change

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-1-alt.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-2.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-3.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-5-1-general-check-your-answers.html

General directions order

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-1-old.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-1.html

Order update

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-3-2-production.html
app/views/r2/x-ui/case-worker/case-worker-general-directions-order-4-2-production-check-your-answers.html

Case worker files

---

app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-1.html

Changes to 1243

---

app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-2.html
app/views/r2/x-ui/case-worker/case-worker-gatekeeping-order-3.html

1340 still missing additional paragraphs mechanism

---

app/views/r2/x-ui/case-worker/final-adoption-order-1.html
app/views/r2/x-ui/case-worker/final-adoption-order-3.html

Routing of final adoption order to check your answers

---

app/views/r2/x-ui/case-worker/gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/gatekeeping-order-2.html
app/views/r2/x-ui/case-worker/gatekeeping-order-3.html

Gatekeeping order updates from Lisa's content

---

app/views/includes/xui-header.html
app/views/layout-xui.html
app/views/r2/index.html
app/views/r2/x-ui/case-worker/final-adoption-order-2.html
app/views/r2/x-ui/case-worker/final-adoption-order-4-check-your-answers.html
app/views/r2/x-ui/case-worker/gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/gatekeeping-order-2.html

Gatekeeping order changes for ticket 1243

---

app/data/session-data-defaults.js
app/views/r2/x-ui/case-worker/gatekeeping-order-2.html
app/views/r2/x-ui/case-worker/gatekeeping-order-3.html

Gatekeeping order pages 2 and 3 updates

---

app/views/r2/x-ui/case-worker/final-adoption-order-1.html
app/views/r2/x-ui/case-worker/gatekeeping-order-4-select-recipient.html

Party changed to person

---

app/views/r2/x-ui/case-worker/gatekeeping-order-3.html

Gatekeeping order changes from ticket 1340

---

app/views/r2/x-ui/case-worker/gatekeeping-order-check-your-answers.html

Gatekeeping order

---

app/views/r2/x-ui/case-worker/gatekeeping-order-check-your-answers.html

Gatekeeping check your answers changes based on changes to page 3

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/final-adoption-order-1.html

Final adoption start of journey update

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/final-adoption-order-1.html

Final adoption order

---

app/views/r2/x-ui/case-worker/gatekeeping-order-4-select-recipient.html

Gatekeeping recipients removal of respondents

---

app/views/r2/x-ui/case-worker/gatekeeping-order-3.html

Gatekeeping removal of date on leave to oppose

---

app/views/r2/x-ui/case-worker/gatekeeping-order-2.html

Change length of hearing to free text

---

app/views/r2/citizen-dashboard-old/all-applications-table.html
app/views/r2/citizen-dashboard-old/all-applications.html
app/views/r2/citizen-dashboard-old/citizen-dashboard-mary.html
app/views/r2/citizen-dashboard-old/index.html
app/views/r2/citizen-dashboard-old/view-application.html
app/views/r2/citizen-dashboard/test.html
app/views/r2/x-ui/case-worker/gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/gatekeeping-order-4-select-recipient.html
app/views/r2/x-ui/case-worker/gatekeeping-order-check-your-answers.html
app/views/r2/x-ui/case-worker/other-parties.html
app/views/r2/x-ui/case-worker/test.html

Replace CAFCASS with Cafcass on all occurrences

---

app/views/r2/citizen-dashboard/test.html

Test citizen dashboard

---

app/assets/sass/components/_progress-bar.scss
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/bringsupport.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/checkanswers.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/checkanswerscopy.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/checkanswersreqs.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/communication.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/courthearings.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/courtorder.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/documents.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/factors.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/intermediary.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/languagerequirements.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/preventfromparticipating.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/remotehearing.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/safetyrequirements.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/specialarrangements.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/specialassistance.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/start.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/tofeelcomfortable.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/travelsupport.html
app/views/r2/citizen-dashboard/aboutyou/tellusyourhearingneeds/welshelanguage.html
app/views/r2/citizen-dashboard/index.html

Hearing needs

---

app/views/r2/index.html

index updated to show citizen dashboard link

---

app/views/r2/citizen-dashboard-version-1/index.html

Removal of link for second application on version 1 citizen dashboard

---

app/views/r2/citizen-dashboard/index.html
app/views/r2/x-ui/case-worker/gatekeeping-order-2.html

Cafcass added to gatekeeping order

---

app/views/r2/x-ui/case-worker/gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/gatekeeping-order-2.html
app/views/r2/x-ui/case-worker/gatekeeping-order-check-your-answers.html

Cafcass changes to gatekeeping order

---

app/views/r2/citizen-dashboard/index.html

Removal of one step on citizen dashboard

---

app/views/r2/citizen-dashboard/index.html
app/views/r2/citizen-dashboard/respond-to-question/are-you-responding-to-query-from-court.html
app/views/r2/citizen-dashboard/respond-to-question/have-you-been-asked-to-submit-document.html
app/views/r2/citizen-dashboard/respond-to-question/responding-to-query.html
app/views/r2/citizen-dashboard/yourhearings/hearings.html
app/views/r2/routes.js

Hearings section added to citizen dashboard

---

app/views/r2/citizen-dashboard/respond-to-question/are-you-responding-to-query-from-court.html
app/views/r2/citizen-dashboard/yourhearings/hearings.html

Test following heroku error

---

app/views/r2/citizen-dashboard/respond-to-question/what-do-you-need-to-do.html

Heroku failing recovery push

---

app/data/session-data-defaults.js
app/views/r2/citizen-dashboard/index.html
app/views/r2/citizen-dashboard/respond-to-query/check-your-answers.html
app/views/r2/citizen-dashboard/respond-to-query/query.html
app/views/r2/citizen-dashboard/respond-to-query/question.html
app/views/r2/citizen-dashboard/yourhearings/first-hearing-not-bold.html
app/views/r2/routes.js

Added application document again

---

app/views/r2/x-ui/case-worker/final-adoption-order-1.html
app/views/r2/x-ui/case-worker/final-adoption-order-5-check-your-answers.html
app/views/r2/x-ui/case-worker/gatekeeping-order-1.html

Date order made added to gatekeeping and final adoption orders

---

app/views/r2/x-ui/case-worker/gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/gatekeeping-order-2.html
app/views/r2/x-ui/case-worker/gatekeeping-order-check-your-answers.html
app/views/r2/x-ui/case-worker/old-flows/final-adoption-order-2.html

Gatekeeping order changes

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/gatekeeping-order-6-order-preview.html

Change of order of flow on gatekeeping order

---

app/views/r2/x-ui/case-worker/final-adoption-order-4-preview-draft.html
app/views/r2/x-ui/case-worker/gatekeeping-order-6-order-preview.html

Gatekeeping order preview order changed to before check your answers

---

app/views/r2/citizen-dashboard/respond-to-query/are-you-responding-to-query-from-court.html
app/views/r2/citizen-dashboard/respond-to-query/ask-question.html
app/views/r2/citizen-dashboard/respond-to-query/check-your-answers.html
app/views/r2/citizen-dashboard/respond-to-query/question.html
app/views/r2/citizen-dashboard/respond-to-query/response-question-1.html
app/views/r2/citizen-dashboard/respond-to-query/upload.html
app/views/r2/citizen-dashboard/respond-to-query/what-do-you-need-help-with.html
app/views/r2/citizen-dashboard/respond-to-query/what-has-court-requested.html

Citizen dashboard updated links on R2

---

app/views/r2/x-ui/case-worker/final-adoption-order-1.html
app/views/r2/x-ui/case-worker/final-adoption-order-3-recipients.html

Changed to gatekeeping prototype from ticket 1318

---

app/views/r2/routes.js

Link to orders from gatekeeping order

---

app/views/r2/dss/add-information.html
app/views/r2/dss/case-reference-number.html
app/views/r2/dss/child-details.html
app/views/r2/dss/email.html
app/views/r2/dss/problem.html
app/views/r2/dss/start.html
app/views/r2/routes.js

DSS journey in progress

---

app/views/r2/dss/add-information.html
app/views/r2/dss/child-details.html
app/views/r2/routes.js

Nationalities errors on routes

---

app/views/r2/dss/add-information.html
app/views/r2/dss/case-reference-number.html
app/views/r2/dss/check-your-answers.html
app/views/r2/dss/child-details.html
app/views/r2/dss/confirmation.html
app/views/r2/routes.js

DSS journey minus error messages

---

app/views/r2/dss/add-information.html
app/views/r2/dss/child-details.html
app/views/r2/routes.js

DSS with errors

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/birth-parents.html
app/views/r2/x-ui/case-worker/blank-letter-content.html
app/views/r2/x-ui/case-worker/correspondence.html
app/views/r2/x-ui/case-worker/documents.html
app/views/r2/x-ui/case-worker/index.html
app/views/r2/x-ui/case-worker/messages.html
app/views/r2/x-ui/case-worker/notes.html
app/views/r2/x-ui/case-worker/orders.html
app/views/r2/x-ui/case-worker/other-parties.html
app/views/r2/x-ui/case-worker/payments.html
app/views/r2/x-ui/case-worker/prospective-parents.html
app/views/r2/x-ui/case-worker/seek-further-information-preview.html

Preview letter added to seek further information flow

---

app/views/r2/x-ui/case-worker/seek-further-information-preview.html

Seek further info preview screen

---

app/views/r2/x-ui/case-worker/blank-letter-content.html
app/views/r2/x-ui/case-worker/blank-letter-recipients.html

Blank letter

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/blank-letter-preview

Blank letter preview page added

---

app/views/r2/x-ui/case-worker/final-adoption-order-1.html

Final adoption order tweak to child name after adoption

---

app/views/r2/x-ui/case-worker/correspondence-new.html
app/views/r2/x-ui/case-worker/history.html
app/views/r2/x-ui/case-worker/index.html
app/views/r2/x-ui/case-worker/messages.html
app/views/r2/x-ui/case-worker/notes.html
app/views/r2/x-ui/case-worker/orders.html
app/views/r2/x-ui/case-worker/other-parties.html
app/views/r2/x-ui/case-worker/payments.html
app/views/r2/x-ui/case-worker/prospective-parents.html

Correspondence tab on caseworker always visible

---

app/views/r2/x-ui/case-worker/documents.html

Correspondence tab on documents

---

app/views/r2/x-ui/case-worker/gatekeeping-order-3.html

Gatekeeping order save as draft radios

---

app/views/r2/routes.js
app/views/r2/x-ui/case-worker/final-adoption-order-2.html
app/views/r2/x-ui/case-worker/final-adoption-order-3-recipients.html
app/views/r2/x-ui/case-worker/final-adoption-order-4-preview-draft.html
app/views/r2/x-ui/case-worker/final-adoption-order-5-check-your-answers.html

Final adoption order changes

---

app/views/r2/x-ui/case-worker/final-adoption-order-4-preview-draft.html
app/views/r2/x-ui/case-worker/final-adoption-order-5-check-your-answers.html
app/views/r2/x-ui/case-worker/gatekeeping-order-check-your-answers.html

Final adoption order preview page and buttons change

---

app/views/r2/x-ui/case-worker/draft-orders.html
app/views/r2/x-ui/case-worker/final-adoption-order-2.html
app/views/r2/x-ui/case-worker/gatekeeping-order-3.html

Draft order

---

app/views/r2/x-ui/case-worker/correspondence.html
app/views/r2/x-ui/case-worker/documents.html
app/views/r2/x-ui/case-worker/draft-orders.html
app/views/r2/x-ui/case-worker/history.html
app/views/r2/x-ui/case-worker/messages.html
app/views/r2/x-ui/case-worker/notes.html
app/views/r2/x-ui/case-worker/orders.html
app/views/r2/x-ui/case-worker/other-parties.html
app/views/r2/x-ui/case-worker/payments.html
app/views/r2/x-ui/case-worker/prospective-parents.html

Draft orders added to the tabs on all pages

---

app/views/r2/x-ui/case-worker/blank-letter-recipients.html

Change to cafcass

---

app/views/r2/x-ui/case-worker/blank-letter-check-your-answers.html
app/views/r2/x-ui/case-worker/blank-letter-recipients.html
app/views/r2/x-ui/case-worker/draft-orders.html

Success message updated on draft orders tab

---

app/views/r2/x-ui/case-worker/final-adoption-order-3-recipients.html

Final adoption order recipients H1 change

---

app/data/session-data-defaults.js
app/views/r2/routes.js
app/views/r2/task-list.html

Tags added to defaults file

---

app/data/session-data-defaults.js
app/views/r2/routes.js

LA portal fix of broken tags

---

app/data/session-data-defaults.js

Session defaults update

---

app/views/r2/x-ui/case-worker/gatekeeping-order-1.html
app/views/r2/x-ui/case-worker/gatekeeping-order-3.html

made changes to gatekeeping order creation pages.
```
[ ] Yes
[ ] No
```

branch-02023-changes

---

app/views/r2/eligibility/start-placement-2.html
app/views/r2/la-portal/sibling-summary.html
app/views/r2/la-portal/task-list.html
app/views/r2/routes.js
app/views/r2/task-list.html
app/views/stored-data.html

Task list functionality updates
